"""Novo banco

Revision ID: 10ec96d3e3eb
Revises: 
Create Date: 2023-05-31 16:47:35.598111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ec96d3e3eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('nf', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cicloestudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome_ciclo', sa.String(length=100), nullable=True),
    sa.Column('duracao_ciclo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ciclo_assunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=True),
    sa.Column('id_assunto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['cicloestudo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horasestudadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_assunto', sa.Integer(), nullable=True),
    sa.Column('inicio_estudo', sa.DateTime(), nullable=True),
    sa.Column('fim_estudo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cicloassunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_assunto', sa.Integer(), nullable=True),
    sa.Column('id_estudo', sa.Integer(), nullable=True),
    sa.Column('id_horasestudo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['id_estudo'], ['cicloestudo.id'], ),
    sa.ForeignKeyConstraint(['id_horasestudo'], ['horasestudadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cicloassunto')
    op.drop_table('horasestudadas')
    op.drop_table('ciclo_assunto')
    op.drop_table('cicloestudo')
    op.drop_table('assunto')
    op.drop_table('usuario')
    # ### end Alembic commands ###
