"""Novo banco 2

Revision ID: 8d264b08f6f5
Revises: 10ec96d3e3eb
Create Date: 2023-05-31 16:50:17.552820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d264b08f6f5'
down_revision = '10ec96d3e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cicloassunto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cicloassunto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_assunto', sa.INTEGER(), nullable=True),
    sa.Column('id_estudo', sa.INTEGER(), nullable=True),
    sa.Column('id_horasestudo', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['id_estudo'], ['cicloestudo.id'], ),
    sa.ForeignKeyConstraint(['id_horasestudo'], ['horasestudadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
